name: Hello World Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          aws sts get-caller-identity